# Generated by Django 5.1.15 on 2026-01-25 21:11

import apps.users.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Date and time when the record was soft deleted', null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active', verbose_name='Is Active')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this record is published publicly', verbose_name='Is Published')),
                ('version', models.PositiveIntegerField(default=1, editable=False, help_text='Record version number', verbose_name='Version')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Custom sorting order (lower numbers appear first)', verbose_name='Sort Order')),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email already exists'}, help_text="User's email address", max_length=254, unique=True, verbose_name='Email')),
                ('tax_id', models.CharField(help_text='User tax identification number, e.g CPF, CIN, CNPJ, etc.', max_length=14, unique=True, verbose_name='Tax iD')),
                ('date_of_birth', models.DateField(help_text="User's date of birth", verbose_name='Date of birth')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tax_id'], name='users_user_tax_id_91ea78_idx'), models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['date_of_birth'], name='users_user_date_of_7e45e1_idx')],
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
    ]
