# Generated by Django 5.1.15 on 2026-01-29 23:35

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import localflavor.br.models
import src.apps.institutions.models.models_net
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionChoicesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Date and time when the record was soft deleted', null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active', verbose_name='Is Active')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this record is published publicly', verbose_name='Is Published')),
                ('version', models.PositiveIntegerField(default=1, editable=False, help_text='Record version number', verbose_name='Version')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Custom sorting order (lower numbers appear first)', verbose_name='Sort Order')),
                ('institution_choices_type_name', models.CharField(help_text='Name of the institution types', max_length=50, unique=True, verbose_name='institution_choices_type')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Institution Type',
                'verbose_name_plural': 'Institution Types',
                'db_table': 'institution_types',
                'db_table_comment': 'institution_types table, used by only Institutions',
                'ordering': ['institution_choices_type_name'],
            },
        ),
        migrations.CreateModel(
            name='NetSchools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Date and time when the record was soft deleted', null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active', verbose_name='Is Active')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this record is published publicly', verbose_name='Is Published')),
                ('version', models.PositiveIntegerField(default=1, editable=False, help_text='Record version number', verbose_name='Version')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Custom sorting order (lower numbers appear first)', verbose_name='Sort Order')),
                ('parent_company_name', models.CharField(max_length=100, verbose_name='name of the parent company')),
                ('legal_name', models.CharField(max_length=100, verbose_name='legal_name')),
                ('trade_name', models.CharField(max_length=100, verbose_name='trade_name')),
                ('tax_identification_number', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$|^\\d{14}$', message='Invalid format for CNPJ.Use 00.000.000/0000-00 ou 00000000000000.'), src.apps.institutions.models.models_net.validate_cnpj], verbose_name='CNPJ')),
                ('foundation_date', models.DateField(verbose_name='foundation_date')),
                ('institution_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='networks', to='institutions.institutionchoicestype', verbose_name='institution_type')),
                ('owner', models.ForeignKey(help_text='Find', on_delete=django.db.models.deletion.PROTECT, related_name='school_networks', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'School Network',
                'verbose_name_plural': 'School Networks',
                'db_table_comment': 'Educational institution networks',
                'ordering': ['trade_name'],
            },
        ),
        migrations.CreateModel(
            name='AddressNetSchools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('billing', 'Billing'), ('shipping', 'Shipping'), ('other', 'Other')], default='home', help_text='Purpose of this address', max_length=25, verbose_name='address type')),
                ('country', django_countries.fields.CountryField(default='BR', max_length=2, verbose_name='country')),
                ('state', localflavor.br.models.BRStateField(max_length=2, verbose_name='state')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('district', models.CharField(help_text='Neighborhood or district name', max_length=100, verbose_name='district')),
                ('street', models.CharField(help_text='Street, avenue, etc.', max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='street')),
                ('number', models.CharField(help_text="Building/house number. Use 'S/N' for no number.", max_length=10, validators=[django.core.validators.RegexValidator('^(\\d+|S/N)$', message="Number must contain digits or be 'S/N'.")], verbose_name='number')),
                ('complement', models.CharField(blank=True, help_text='Apartment, floor, block, etc.', max_length=100, verbose_name='complement')),
                ('zip_code', models.CharField(help_text='ZIP code', max_length=20, verbose_name='zip code')),
                ('net_school_address', models.ForeignKey(help_text='address of the school network', on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='institutions.netschools', verbose_name='net_school_address')),
            ],
            options={
                'verbose_name': 'Net School Address',
                'verbose_name_plural': 'Net School Addresses',
            },
        ),
        migrations.AddIndex(
            model_name='netschools',
            index=models.Index(fields=['trade_name'], name='institution_trade_n_af3404_idx'),
        ),
        migrations.AddIndex(
            model_name='netschools',
            index=models.Index(fields=['legal_name'], name='institution_legal_n_0d9ebb_idx'),
        ),
    ]
